version: "3"

services:
  mysql_db:
    container_name: "mysql_db"
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db_volume:/var/lib/mysql
    environment: # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: employees
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-tier
  python5:
    restart: always
    build: .
    container_name: "python5"
    working_dir: "/root/"
    tty: true
    depends_on:
      - mysql_db
    networks:
      - app-tier
    volumes:
      - .:/root
      - pycache_volume:/root/.cache


networks:
  app-tier:
    driver: bridge

volumes:
  db_volume:
  pycache_volume:
